language: php

php:
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

before_deploy:
  - ./dist-create.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: kiln.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_script:
  - vendor/bin/coveralls --config .coveralls.yml --verbose --exclude-no-stmt