language: php

php:
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

after_script:
  - vendor/bin/coveralls --config .coveralls.yml --verbose --exclude-no-stmt