awsConfig:
  # see http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sts.html#creating-a-client
  region: us-west-2
  # The AWS CLI Profile.
  # Not needed if running on EC2 launched with appropriate Role
  profile:
appConfig:
  # one of
  #  error
  #  warning
  #  info
  #  debug
  logLevel: debug
sqsConfig:
  amiBuildRequestQueueUrl:
packer:
  executablePath: /usr/bin/container-packer
  # awsAccessKey & awsSecretKey not needed if running on EC2 launched with appropriate Role
  # awsAccessKey: null
  # awsSecretKey: null
templates:
  templatesRepo: 'https://github.com/<YOUR REPO PATH>.git'
  checkoutPath: /home/ec2-user/packer-build-templates
executionDigest:
  bucketName: