appConfig:
  # one of
  #  error
  #  warning
  #  info
  #  debug
  logLevel: debug
awsConfig:
  # see http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-sts.html#creating-a-client
  region: us-west-2
  # profile not needed if running on EC2 launched with appropriate Role
  # profile: default
sqsConfig:
  amiBuildRequestQueueName: ami-build-requests
  # see http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sqs.SqsClient.html#_getQueueAttributes
  queueAttributes:
    VisibilityTimeout: 1200
    MessageRetentionPeriod: 345600
    # 256KB is the max
    MaximumMessageSize: 256000
    ReceiveMessageWaitTimeSeconds: 0
    DelaySeconds: 0
packer:
  executablePath: /usr/bin/container-packer
  # awsAccessKey & awsSecretKey not needed if running on EC2 launched with appropriate Role
  # awsAccessKey: null
  # awsSecretKey: null
templates:
  templatesRepo: 'git@github.com:<YOUR REPO PATH>'
  checkoutPath: /home/ec2-user/packer-build-templates
executionDigest:
  bucketName: seedling-digests